#include "styles.h"

// Default initialization of colours
vec4f HOVERED_COLOUR(DEFAULT_HOVERED_COLOUR);
vec4f ACTIVE_COLOUR(DEFAULT_ACTIVE_COLOUR);
vec4f INHIBITED_COLOUR(DEFAULT_INHIBITED_COLOUR);
vec4f UNITS_COLOUR(DEFAULT_UNITS_COLOUR);
vec4f BACKGROUND_COLOUR(DEFAULT_BACKGROUND_COLOUR);
