#include "styles.h"

// Default initialization of colours
vec4f HOVERED_COLOUR(DEFAULT_HOVERED_COLOUR);
vec4f SELECTED_COLOUR(DEFAULT_SELECTED_COLOUR);
vec4f UNITS_COLOUR(DEFAULT_UNITS_COLOUR);
vec4f BACKGROUND_COLOUR(DEFAULT_BACKGROUND_COLOUR);
